# Generated by Django 5.1.3 on 2024-12-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.FileField(default='/static/images/user-profile.png', upload_to='user-image'),
        ),
    ]
