# Generated by Django 5.1.3 on 2024-12-30 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_image',
            new_name='profile_picture',
        ),
    ]
