# Generated by Django 5.1.3 on 2025-01-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(default='/media/user_profile_image/user-profile.png', upload_to='media/user_profile_image'),
        ),
    ]
