# Generated by Django 5.1.3 on 2025-01-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(default='user_profile_image/user-profile.png', upload_to='user_profile_image'),
        ),
    ]
