# Generated by Django 5.1.3 on 2025-02-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='1231231231', max_length=100, null=True),
        ),
    ]
