# Generated by Django 5.1.3 on 2024-12-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('select_website', models.CharField(choices=[('Portfolio', 'Portfolio'), ('E-Commerce', 'E-Commerce'), ('Corporate', 'Corporate'), ('Educational', 'Educational'), ('Blog', 'Blog'), ('News', 'News'), ('Non-Profit', 'Non-Profit'), ('Landing Page', 'Landing Page'), ('Other', 'Other')], null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
