# Generated by Django 5.1.3 on 2024-12-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='select_website',
            field=models.CharField(blank=True, choices=[('Portfolio', 'Portfolio'), ('E-Commerce', 'E-Commerce'), ('Corporate', 'Corporate'), ('Educational', 'Educational'), ('Blog', 'Blog'), ('News', 'News'), ('Non-Profit', 'Non-Profit'), ('Landing Page', 'Landing Page'), ('Other', 'Other')], null=True),
        ),
    ]
