# Generated by Django 5.1.3 on 2024-11-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, null=True)),
                ('project_title', models.CharField(max_length=255, null=True)),
                ('project_description', models.TextField(null=True)),
                ('project_image', models.FileField(upload_to='project_image')),
                ('project_video', models.FileField(upload_to='project_video')),
                ('project_category', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.IntegerField(default=0)),
            ],
        ),
    ]
