# Generated by Django 5.1.3 on 2024-12-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_client_name_project_external_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_thumbnail',
            field=models.FileField(null=True, upload_to='project_image'),
        ),
    ]
