# Generated by Django 5.1.3 on 2024-12-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_call', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='requirement',
            field=models.CharField(choices=[('Portfolio', 'Portfolio'), ('Custom', 'Custom'), ('Ecommerce', 'Ecommerce'), ('Other', 'Other')], max_length=255, null=True),
        ),
    ]
