# Generated by Django 5.1.3 on 2024-12-28 13:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_call', '0002_room_message_room_requirement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='VideoRoom',
        ),
    ]
