# Generated by Django 5.1.3 on 2024-12-30 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_call', '0004_chatmessage_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='chatroom',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_chatmessage', to='video_call.chatroom'),
        ),
    ]
