# Generated by Django 5.1.3 on 2024-12-30 16:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_call', '0005_chatmessage_chatroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=100, null=True),
        ),
    ]
